### ISSUE TITLE
[FeatureRequest] Change Device shown on Garmin Connect

### ISSUE THREAD

**Issue by fr1ffo** [philosowaffle/peloton-to-garmin#134]
Regarding device types - is there any method to put our own Garmin device into the configuration.local.json? It seems that inside the /src/Conversion/FitConverter.cs it has the _productId hardcoded to a Forerunner 945 (line 17, if needed).

 - OS: docker
 - Method: docker
 - Version: latest

Thank you!

**Comment by manc74** [comment]
I was looking for this too. I have a fenix 6x Pro and would be great to have the ability to have my rides logged with the right hardware.

**Comment by philosowaffle** [comment]
Right now, on V2 there is no way to customize the device used.  But I can add support for this.

Just want to mention, that as far as I can tell, adjusting this to reflect your personal device will be nothing more than a cosmetic change on Garmin Connect which is why I did not initially carry the feature forward from V1. But this is the third time its been mentioned recently so it seems to be a desired feature.

**Comment by philosowaffle** [comment]
**Requirements:**
1. P2G should look for a `device_info.xml` file in the current working directory ([sample](https://github.com/philosowaffle/peloton-to-garmin/blob/master/device_info.sample.xml))
    1. Alternatively, we could expose an enum that could be configured via the config file.  The user would simply set their desired device name and P2G would apply it. This would be similar to how the [Garmin SDK](https://github.com/philosowaffle/peloton-to-garmin/blob/master/src/Conversion/FitConverter.cs#L17) defines device types.
2. If this file exists, then it should be used to set the Device info on the FIT file (and TCX?)
3. If this file does not exist, then it should use the current default device
4. The wiki should be updated to explain how to get and setup a custom device info file
