### ISSUE TITLE
[Feature] Ability to pull Strenght Metrics from Guide API

### ISSUE THREAD

**Issue by milleruk** [philosowaffle/peloton-to-garmin#436]
Fantastic tool - is it possible to review the API to pull the metrics if the activity has been performed with the Guide

**Comment by philosowaffle** [comment]
Hi @milleruk 👋 

It would be most helpful for me to see some example workout data generated from a Guide.  The easiest way for me to get this info is if you add me on Peloton (@cyclesaurus).  As a follower, I will be able to see some of your Guide workouts, and I can use that to explore the API data and investigate what support could be added to P2G.  Once I have some of that data we can un-follow each other.

A second option (if you'd rather not add a complete stranger from the internet) is to modify your [Format settings](https://philosowaffle.github.io/peloton-to-garmin/configuration/json.html#format-config) to include:
```json
"SaveLocalCopy": true,
"Json": true,
``` 

After applying these setting changes, you can run a sync job that would pick up a recent Guide workout, and the sample json data should get saved to your [OutputDirectory](https://philosowaffle.github.io/peloton-to-garmin/configuration/json.html#app-config).  Upload that file here, and I can take a look.

**Comment by milleruk** [comment]
Cheers, Have followed 

The output is great so far as it still picks them up but it would just save me 15 mins of manually entering the sets - although some of the peloton names do not match up with garmin so that may have to be considered when creating a filter to match them

Also a link to the JSON file is here - https://pastebin.com/WZqmc4eJ

**Comment by philosowaffle** [comment]
Finally got this working, only downside is P2G has to provide a [manual mapping from PelotonExercise => GarminExercise](https://github.com/philosowaffle/peloton-to-garmin/blob/master/src/Conversion/ExerciseMapping.cs#L8).  Will take some time and help from the community to build up this mapping library.  I started out by going through your workout history (@millruk) and adding mapping for your most recent handful of strength workouts, so hopefully that covers some of the most popular movements.

When unknown exercises are detected, P2G will:
1. Skip the exercise, it won't get added to your Garmin workout
2. Write the Peloton Exercise information as an error log message so these can easily be reported

Additionally, when an exercise is done for Time instead of for Reps, P2G will estimate how many reps were completed during the time.  This will allow Garmin to better represent Load and Muscle Score.  The logic is:

```
durationOfExercise / defaultSecondsPerRep = reps

15s Bicep Curls / 3 seconds per rep = 5 reps
```

`DefaultSecondsPerRep` is [configurable in the settings](https://philosowaffle.github.io/peloton-to-garmin/configuration/json.html#format-config) and defaults to `3`.
