### ISSUE TITLE
Peloton Gym - Add partial support

### ISSUE THREAD

**Issue by mapperist** [philosowaffle/peloton-to-garmin#502]
It's appears that I can't download Peloton Gym workouts. I see it try 4 times but the result is always "ride not found."

This is via docker on an Ubuntu server.

**Comment by mapperist** [comment]
I deleted the gym workout and I'm able to download the 4 previous workouts before it (again).

**Comment by philosowaffle** [comment]
For now I have made the necessary changes so that Peloton Gym workouts do not cause errors in P2G and will atleast upload some minimal data.  These changes should be available on the `latest` tags.

Full support for Peloton Gym workouts will take more time and research to figure out so I've created a separate ticket for that: #505.
