### ISSUE TITLE
Getting error 127 on manual sync jobs 

### ISSUE THREAD

**Issue by gunjanmarwah** [philosowaffle/peloton-to-garmin#573]
**Describe the bug**
Ran it twice, no other changes to the code recently. 

**To Reproduce**
1. Go to the manual sync job history? I am not a dev and don't really know how to navigate this well!

**Expected behavior**
Should have run

**Logs**
Error 127

**Comment by gunjanmarwah** [comment]
Error: Process completed with exit code 127.

**Comment by RCornish74** [comment]
I was seeing the same.  After pulling in the latest master branch, I get a startup failure when trying to run the github action

**Comment by benmwatson** [comment]
I'm also getting this, for a couple of days now.

**Comment by philosowaffle** [comment]
Thank you @RCornish74 for mentioning that y'all are running this as a GitHub Action, that helped narrow down the problem.

I suspect y'all's GitHub action is likely pointed at the `latest` tag.  You can find that by looking at this [line](https://github.com/gunjanmarwah/peloton-to-garmin/blob/master/.github/workflows/sync_peloton_to_garmin.yml#L20) in your respective repositories. What this means is that every time the Action runs, it checks to see if there is a newer version of P2G available, and if so it grabs that latest version and runs it.  While that may sound like a good thing, occasionally P2G needs to introduce breaking changes that are not backwards compatible.  In these cases it can cause an error to occur.

Two days ago, v4 of P2G was [released](https://github.com/philosowaffle/peloton-to-garmin/releases).  Upgrading to this version requires some changes to the GitHub Action.

There are two options:

1. Stay on the version you were previously using.  To do this you will need to modify [this line](https://github.com/gunjanmarwah/peloton-to-garmin/blob/master/.github/workflows/sync_peloton_to_garmin.yml#L20) to be `image:  philosowaffle/peloton-to-garmin:v3.6.1`.
2. Upgrade to version 4.  Instructions can be found [here](https://philosowaffle.github.io/peloton-to-garmin/latest/install/github-action/#updating) (under the Updating section).  Please make note of any custom configuration you have made first as you will need to re-apply these changes after syncing.

**Comment by gunjanmarwah** [comment]
That did the trick! And while I was in there, I figured out how to update
my time zone to EST lol. Thanks!

Gunjan Marwah Nichani

**Comment by RCornish74** [comment]
Mine was a bit more involved, but I got it working as well

I had synced the latest changes from the fork and had to merge conflicts, but I ended up using `console-stable` rather than `console-latest`. Based on your @philosowaffle's comment I updated that back to `console-stable`

Then my github action was still failing. I was able to find an error related to the github action startup failure 
<img width="1232" alt="image" src="https://github.com/philosowaffle/peloton-to-garmin/assets/42150128/eb9f018a-bceb-4b22-8397-78564e719909">

I did some googling based on that error and realized that it was related to security settings on actions on my github account. I ended up changing from 
<img width="1499" alt="Screenshot 2023-12-12 at 9 42 00 AM" src="https://github.com/philosowaffle/peloton-to-garmin/assets/42150128/a091a078-c275-4b8e-93f1-4d332daa17ec">
to instead have the following, and then it ran without issues 
<img width="1517" alt="Screenshot 2023-12-12 at 9 43 00 AM" src="https://github.com/philosowaffle/peloton-to-garmin/assets/42150128/0993c270-0087-49e1-a5dd-30b8ff880d24">
